# Generated by Django 6.0.7 on 2026-08-04 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('post_nom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('email', models.CharField(max_length=254, unique=True, verbose_name='Identifiant')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['nom', 'post_nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id_filiere', models.AutoField(primary_key=True, serialize=False)),
                ('nom_filiere', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['nom_filiere'],
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id_fonction', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
                'ordering': ['intitule'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id_prom', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=200)),
                ('annee_academique', models.CharField(max_length=20)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.filiere')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-annee_academique', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id_horaire', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(help_text='ex: Semestre 1 - 2026', max_length=200)),
                ('type_horaire', models.CharField(choices=[('COURS', 'Cours'), ('EXAMEN', 'Examen')], default='COURS', help_text="Type d'horaire : Cours ou Examen", max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PROPOSED', 'Proposé (Chef Filière)'), ('CONFIRMED', 'Confirmé (SGA)'), ('PUBLISHED', 'Publié')], default='DRAFT', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='core.promotion')),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id_cours', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('duree', models.PositiveIntegerField(help_text='Durée en minutes')),
                ('promotion', models.ForeignKey(blank=True, help_text='Promotion à laquelle ce cours est associé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='core.promotion')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('id_util', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_associes', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
            options={
                'verbose_name': 'Association rôle',
                'verbose_name_plural': 'Associations rôle',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('num_matric', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_naiss', models.DateField(blank=True, null=True)),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='core.promotion')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'abstract': False,
            },
            bases=('core.utilisateur',),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('fonction', models.ForeignKey(blank=True, help_text='Fonction occupée par le personnel (Chef de Filière, Enseignant, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels', to='core.fonction')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnels',
                'abstract': False,
            },
            bases=('core.utilisateur',),
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('note', models.TextField(blank=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='core.personnel')),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
                'ordering': ['enseignant', 'jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Creneau_Horaire',
            fields=[
                ('id_chrono', models.AutoField(primary_key=True, serialize=False)),
                ('type_horaire', models.CharField(choices=[('COURS', 'Cours'), ('EXAMEN', 'Examen')], default='COURS', help_text='Type de créneau : Cours (jour hebdomadaire) ou Examen (date précise)', max_length=10)),
                ('date', models.DateField(blank=True, help_text='Date précise pour un examen (ex: 15/06/2026). Laisser vide pour un cours hebdomadaire.', null=True)),
                ('heure', models.CharField(choices=[('08:00:00', '08:00'), ('11:40:00', '11:40')], default='08:00:00', help_text='Heure du créneau (08:00 ou 11h40)', max_length=10)),
                ('jours', models.CharField(blank=True, choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], help_text='Jour de la semaine pour un cours hebdomadaire. Laisser vide pour un examen avec date.', max_length=20, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PROPOSED', 'Proposé (Chef Filière)'), ('CONFIRMED', 'Confirmé (SGA)'), ('PUBLISHED', 'Publié')], default='DRAFT', max_length=20)),
                ('annotations', models.TextField(blank=True, help_text="Annotations ou demandes de modification de l'enseignant", null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='core.cours')),
                ('horaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux', to='core.horaire')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_cours', to='core.personnel')),
            ],
            options={
                'verbose_name': 'Créneau Horaire',
                'verbose_name_plural': 'Créneaux Horaires',
                'ordering': ['date', 'jours', 'heure'],
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(blank=True, help_text='Enseignant habilité à dispenser ce cours', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_assignes', to='core.personnel'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(fields=('designation', 'annee_academique', 'filiere'), name='unique_promotion_filiere_annee'),
        ),
        migrations.AlterUniqueTogether(
            name='utilisateur_role',
            unique_together={('id_util', 'role')},
        ),
        migrations.AddConstraint(
            model_name='creneau_horaire',
            constraint=models.UniqueConstraint(fields=('date', 'heure', 'personnel'), name='unique_creneau_date_personnel'),
        ),
        migrations.AddConstraint(
            model_name='creneau_horaire',
            constraint=models.UniqueConstraint(condition=models.Q(('date__isnull', True)), fields=('jours', 'heure', 'personnel'), name='unique_creneau_jour_personnel'),
        ),
    ]
