# Generated by Django 6.0.7 on 2026-08-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilite',
            options={'ordering': ['enseignant', 'jour', 'heure'], 'verbose_name': 'Disponibilité', 'verbose_name_plural': 'Disponibilités'},
        ),
        migrations.RenameField(
            model_name='disponibilite',
            old_name='heure_debut',
            new_name='heure',
        ),
        migrations.RemoveField(
            model_name='disponibilite',
            name='heure_fin',
        ),
    ]
