# Generated by Django 6.0.7 on 2026-08-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_disponibilite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='duree_unite',
            field=models.CharField(choices=[('H', 'Heures'), ('MIN', 'Minutes')], default='H', help_text='Unité de la durée (heures par défaut)', max_length=10),
        ),
        migrations.AlterField(
            model_name='cours',
            name='duree',
            field=models.PositiveIntegerField(help_text='Durée en heures (ex: 30H)'),
        ),
    ]
