# Generated by Django 6.0.7 on 2026-07-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_chrono_horaire_jours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chrono_horaire',
            options={'ordering': ['jours', 'heure'], 'verbose_name': 'Horaire', 'verbose_name_plural': 'Horaires'},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['titre'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='disponibilite',
            options={'ordering': ['enseignant', 'jour', 'heure_debut'], 'verbose_name': 'Disponibilité', 'verbose_name_plural': 'Disponibilités'},
        ),
        migrations.AlterModelOptions(
            name='etudiant',
            options={'verbose_name': 'Étudiant', 'verbose_name_plural': 'Étudiants'},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['nom_filiere'], 'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AlterModelOptions(
            name='fonction',
            options={'ordering': ['intitule'], 'verbose_name': 'Fonction', 'verbose_name_plural': 'Fonctions'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-annee_academique', 'designation'], 'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['libelle'], 'verbose_name': 'Rôle', 'verbose_name_plural': 'Rôles'},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['nom', 'post_nom'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='utilisateur_role',
            options={'ordering': ['-date'], 'verbose_name': 'Association rôle', 'verbose_name_plural': 'Associations rôle'},
        ),
        migrations.AddField(
            model_name='chrono_horaire',
            name='promotions',
            field=models.ManyToManyField(blank=True, help_text='Promotions concernées par cet horaire', related_name='horaires', to='core.promotion'),
        ),
        migrations.AlterField(
            model_name='disponibilite',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_naiss',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='num_matric',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
