# Generated by Django 6.0.7 on 2026-07-30 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chrono_horaire_options_alter_cours_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau_Horaire',
            fields=[
                ('id_chrono', models.AutoField(primary_key=True, serialize=False)),
                ('heure', models.TimeField()),
                ('jours', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PROPOSED', 'Proposé (Chef Filière)'), ('CONFIRMED', 'Confirmé (SGA)'), ('PUBLISHED', 'Publié')], default='DRAFT', max_length=20)),
                ('annotations', models.TextField(blank=True, help_text="Annotations ou demandes de modification de l'enseignant", null=True)),
            ],
            options={
                'verbose_name': 'Créneau Horaire',
                'verbose_name_plural': 'Créneaux Horaires',
                'ordering': ['jours', 'heure'],
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id_horaire', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(help_text='ex: Semestre 1 - 2026', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PROPOSED', 'Proposé (Chef Filière)'), ('CONFIRMED', 'Confirmé (SGA)'), ('PUBLISHED', 'Publié')], default='DRAFT', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='chrono_horaire',
            name='unique_creneau_personnel',
        ),
        migrations.AddField(
            model_name='creneau_horaire',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='core.cours'),
        ),
        migrations.AddField(
            model_name='creneau_horaire',
            name='fonction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupations', to='core.fonction'),
        ),
        migrations.AddField(
            model_name='creneau_horaire',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_cours', to='core.personnel'),
        ),
        migrations.AddField(
            model_name='horaire',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='core.promotion'),
        ),
        migrations.AddField(
            model_name='creneau_horaire',
            name='horaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux', to='core.horaire'),
        ),
        migrations.RemoveField(
            model_name='chrono_horaire',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='chrono_horaire',
            name='fonction',
        ),
        migrations.RemoveField(
            model_name='chrono_horaire',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='chrono_horaire',
            name='promotions',
        ),
        migrations.AddConstraint(
            model_name='creneau_horaire',
            constraint=models.UniqueConstraint(fields=('jours', 'heure', 'personnel'), name='unique_creneau_personnel'),
        ),
        migrations.DeleteModel(
            name='Chrono_Horaire',
        ),
    ]
