# Generated by Django 6.0.7 on 2026-07-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_creneau_horaire_horaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaire',
            name='type_horaire',
            field=models.CharField(choices=[('COURS', 'Cours'), ('EXAMEN', 'Examen')], default='COURS', help_text="Type d'horaire : Cours ou Examen", max_length=10),
        ),
    ]
