# Generated by Django 6.0.7 on 2026-07-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_horaire_type_horaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creneau_horaire',
            options={'ordering': ['date', 'jours', 'heure'], 'verbose_name': 'Créneau Horaire', 'verbose_name_plural': 'Créneaux Horaires'},
        ),
        migrations.RemoveConstraint(
            model_name='creneau_horaire',
            name='unique_creneau_personnel',
        ),
        migrations.AddField(
            model_name='creneau_horaire',
            name='date',
            field=models.DateField(blank=True, help_text='Date précise pour un examen (ex: 15/06/2026). Laisser vide pour un cours hebdomadaire.', null=True),
        ),
        migrations.AddField(
            model_name='creneau_horaire',
            name='type_horaire',
            field=models.CharField(choices=[('COURS', 'Cours'), ('EXAMEN', 'Examen')], default='COURS', help_text='Type de créneau : Cours (jour hebdomadaire) ou Examen (date précise)', max_length=10),
        ),
        migrations.AlterField(
            model_name='creneau_horaire',
            name='jours',
            field=models.CharField(blank=True, choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], help_text='Jour de la semaine pour un cours hebdomadaire. Laisser vide pour un examen avec date.', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='creneau_horaire',
            constraint=models.UniqueConstraint(fields=('date', 'heure', 'personnel'), name='unique_creneau_date_personnel'),
        ),
        migrations.AddConstraint(
            model_name='creneau_horaire',
            constraint=models.UniqueConstraint(condition=models.Q(('date__isnull', True)), fields=('jours', 'heure', 'personnel'), name='unique_creneau_jour_personnel'),
        ),
    ]
