# Generated by Django 6.0.7 on 2026-07-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_creneau_horaire_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.CharField(max_length=254, unique=True, verbose_name='Identifiant'),
        ),
    ]
