# Generated by Django 6.0.7 on 2026-07-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau_horaire',
            name='heure',
            field=models.CharField(choices=[('08:00:00', '08:00'), ('11:40:00', '11:40')], default='08:00:00', help_text='Heure du créneau (08:00 ou 11h40)', max_length=10),
        ),
    ]
