# Generated by Django 6.0.7 on 2026-07-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_creneau_horaire_heure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau_horaire',
            name='fonction',
        ),
    ]
