# Generated by Django 6.0.7 on 2026-08-01 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_creneau_horaire_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau_horaire',
            name='fonction',
            field=models.ForeignKey(blank=True, help_text='Type de séance (Cours Théorique, TP, TD, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='core.fonction'),
        ),
    ]
