# Generated by Django 6.0.7 on 2026-08-01 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_creneau_horaire_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau_horaire',
            name='fonction',
            field=models.ForeignKey(blank=True, help_text='Fonction occupée par le personnel dans ce créneau (Chef de Filière, Enseignant, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='core.fonction'),
        ),
    ]
