# Generated by Django 6.0.7 on 2026-08-01 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_creneau_horaire_fonction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau_horaire',
            name='fonction',
        ),
        migrations.AddField(
            model_name='personnel',
            name='fonction',
            field=models.ForeignKey(blank=True, help_text='Fonction occupée par le personnel (Chef de Filière, Enseignant, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels', to='core.fonction'),
        ),
    ]
