# Generated by Django 6.0.7 on 2026-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_creneau_horaire_fonction_personnel_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='enseignants',
            field=models.ManyToManyField(blank=True, help_text='Enseignants habilités à dispenser ce cours', related_name='cours_assignes', to='core.personnel'),
        ),
    ]
