# Generated by Django 6.0.7 on 2026-08-01 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cours_enseignants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='enseignants',
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(blank=True, help_text='Enseignant habilité à dispenser ce cours', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_assignes', to='core.personnel'),
        ),
    ]
