# Generated by Django 6.0.7 on 2026-08-01 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cours_enseignants_cours_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='promotion',
            field=models.ForeignKey(blank=True, help_text='Promotion à laquelle ce cours est associé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='core.promotion'),
        ),
    ]
