from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('schedules/', views.schedule_list, name='schedule_list'),
    path('schedules/edit/', views.edit_schedule, name='create_schedule'),
    path('horaires/create/', views.create_horaire, name='create_horaire'),
    path('schedules/edit/<int:pk>/', views.edit_schedule, name='edit_schedule'),
    path('schedules/publish/<int:pk>/', views.publish_schedule, name='publish_schedule'),
    path('schedules/confirm/<int:pk>/', views.confirm_schedule, name='confirm_schedule'),
    path('schedules/bulk-confirm/', views.bulk_confirm_schedules, name='bulk_confirm_schedules'),
    path('schedules/annotate/<int:pk>/', views.annotate_schedule, name='annotate_schedule'),
    path('availability/', views.submit_availability, name='submit_availability'),
    path('availability/delete/<int:pk>/', views.delete_availability, name='delete_availability'),
    path('teacher/courses/', views.teacher_courses, name='teacher_courses'),
    path('teacher/horaires/', views.teacher_horaires, name='teacher_horaires'),
    path('personnel/', views.manage_personnel, name='manage_personnel'),
    path('personnel/<int:pk>/edit/', views.manage_personnel, name='edit_personnel'),
    path('personnel/<int:pk>/delete/', views.delete_personnel, name='delete_personnel'),
    path('referentiels/<str:type_objet>/', views.manage_referentiel, name='manage_referentiel'),
    path('referentiels/<str:type_objet>/<int:pk>/edit/', views.manage_referentiel, name='edit_referentiel'),
    path('referentiels/<str:type_objet>/<int:pk>/delete/', views.delete_referentiel, name='delete_referentiel'),
    path('students/', views.manage_students, name='manage_students'),
    path('students/<int:pk>/edit/', views.manage_students, name='edit_student'),
    path('students/<int:pk>/delete/', views.delete_student, name='delete_student'),
    path('horaires/', views.horaire_list, name='horaire_list'),
    path('horaires/<int:pk>/', views.view_horaire, name='view_horaire'),
    path('horaires/<int:pk>/edit/', views.edit_horaire, name='edit_horaire'),
    path('horaires/<int:pk>/propose/', views.propose_horaire, name='propose_horaire'),
    path('horaires/<int:pk>/confirm/', views.confirm_horaire, name='confirm_horaire'),
    path('horaires/<int:pk>/publish/', views.publish_horaire, name='publish_horaire'),
    path('horaires/<int:pk>/unpublish/', views.unpublish_horaire, name='unpublish_horaire'),
    path('propositions/', views.propositions_list, name='propositions_list'),
    path('promotions/<int:promotion_id>/generate-horaires/', views.generate_promotion_horaires, name='generate_promotion_horaires'),
    path('promotions/<int:promotion_id>/regenerate-horaires/', views.regenerate_promotion_horaires, name='regenerate_promotion_horaires'),
]
